### ISSUE TITLE
Adjust exposure?

### ISSUE THREAD

**Issue by THECRUSTIEST** [bradleyq/1_16_shaders#9] opened 2021-03-28 07:44 UTC
I like this shader a lot, but it feels like the brightness is too high, even when set to "Moody". For example, sand appears *very* white in most conditions. Is there any way to reduce the exposure or the magnitude of bloom effects? Thanks!

**Comment by Reeses-Puffs** [comment] 2021-03-28 22:30
the only way to do this is to edit the files themselves. as previously stated in the comments in #1, shader config may become possible in the caves and cliffs update with the updated shader system.

**Comment by bradleyq** [comment] 2021-06-08 08:56
dupe of https://github.com/bradleyq/mc_vanilla_shaders/issues/12

**Closed as completed by bradleyq** 2021-06-08 08:56 UTC
